### ISSUE TITLE
Ошибки БЭМ

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/Main-Coon#2]
Не может существовать модификатора без наличия блока. Я имею ввиду `page--active`
https://github.com/StrehaAleksandr/Main-Coon/blob/c21a7ec05b258bdfda2faead2dcd2fa5553096c7/src/index.html#L17

2. Ошибка в именовании класса `pats_paragraf`
https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/index.html#L55

3. Здесь следует добавить класс-элемент `pats__see-more`, т.к. ссылка входит в состав блока `pats`
https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/index.html#L72

4. Это не блок специальных предложений, уместнее имя класса `breed-features`. Пользуйся переводчиком... https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/index.html#L74

5.  Имена классов формируются не по признаку "вид элемента", а по смысловому содержанию. Уместнее будет (с учетом пункта 4) `breed-features__description` https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/index.html#L76

6. Здесь сразу два момента, на оба я указывал ранее (элемент без блока и параграф) https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/index.html#L155

7. Что касается слайдов, то обычно всем слайдам дают один общий класс, в котором описывается общая стилизация слайда, одинаковая для всех, а вторым дают класс-модификатор https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/index.html#L151

8. Социалки тоже следует вынести в отдельный БЭМ-блок https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/index.html#L160

**Comment by StrehaAleksandr** [comment]
Сделал
