### ISSUE TITLE
Грубые ошибки разметки - виды тегов

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/Main-Coon#5]
1. Ссылки
Здесь должна быть ссылка https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/index.html#L369
Читать здесь: https://html5book.ru/hyperlinks-in-html/

2. Дата/время
Для разметки даты и/или времени лучше использовать специальный тег `time`
https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/index.html#L291
Читать тут https://developer.mozilla.org/ru/docs/Web/HTML/Element/time
и тут http://htmlbook.ru/html/time

**Comment by StrehaAleksandr** [comment]
Сделал
