### ISSUE TITLE
БЭМ ошибки в стилях

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/Main-Coon#6]
1. Имя файла должно СТРОГО соответствовать имени БЭМ блока. Расхождения не допускаются https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/scss/components/footer.scss#L1
2. Внутри файла со стилями для одного БЭМ-блока не допускается указание стилей для другого блока 
https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/scss/components/main-header.scss#L9
https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/scss/components/main-header.scss#L17
https://github.com/StrehaAleksandr/Main-Coon/blob/b4f49ee22fe97d77da478ce82caab09e12470a66/src/scss/components/main-header.scss#L34

Это всё - внутри одного и того же файла... Методология БЭМ предполагает четкое структурное разделение блоков

**Comment by StrehaAleksandr** [comment]
Сделал

**Comment by Morfey216** [comment]
Не совсем
https://github.com/StrehaAleksandr/Main-Coon/blob/97b24d150cede93130467cff490b24cf4386003e/src/scss/components/answesrs.scss#L41

И здесь еще https://github.com/StrehaAleksandr/Main-Coon/blob/97b24d150cede93130467cff490b24cf4386003e/src/scss/components/why-us.scss#L51

**Comment by StrehaAleksandr** [comment]
сделал
